config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  devise_for :users
  root to: 'books#index'
  resources :books do
    collection do
      get 'search'
    end
    resource :favorites, only: [:create, :destroy]
  end  
  resources :old_books do
    resources :orders, only: [:index, :create]
  end
  resources :users, only: :show
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :last_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
    validates :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :birth_date
  end  

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX }
  
  has_many :books
  has_many :old_books
  has_many :orders

  has_many :favorites, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @books_read = user.books.where(read_status_id: 2)
    @books_unread = user.books.where(read_status_id: 3)
    @old_books = user.old_books    
  end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class='main'>

<!-- タブ -->
<ul class="tab-list">
  <li class="tab-list-item active">読書投稿（既読）</li>
  <li class="tab-list-item">読書投稿（未読）</li>
  <li class="tab-list-item">古本出品</li>
</ul>

<!-- タブコンテンツ 　-->
<div class="tab-contents">
  <div class="tab-contents-item show">
    <div class="book-bar">
      <%= @nickname %>さんの読書投稿一覧（既読）
      <ul class='book-lists'>
        <% @books_read.each do |book| %>
        <li class='list'>
          <%= link_to book_path(book.id) do %>
          <div class='book-img-content'>
            <%= image_tag book.image_url,  class: "book-img" %>
          </div>
          <div class='book-info'>
            <h3 class='book-name'>
              <%= book.title %>
            </h3>
          </div>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="tab-contents-item">
    <div class="book-bar">
      <%= @nickname %>さんの読書投稿一覧（未読）
      <ul class='book-lists'>
        <% @books_unread.each do |book| %>
        <li class='list'>
          <%= link_to book_path(book.id) do %>
          <div class='book-img-content'>
            <%= image_tag book.image_url,  class: "book-img" %>
          </div>
          <div class='book-info'>
            <h3 class='book-name'>
              <%= book.title %>
            </h3>
          </div>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="tab-contents-item">
    <div class="book-bar">
      <%= @nickname %>さんの古本出品一覧
          <ul class='book-lists'>
            <% @old_books.each do |old_book| %>
        <li class='list'>
          <%= link_to old_book_path(old_book.id) do %>
          <div class='book-img-content'>
            <%= image_tag old_book.image.variant(resize: '400x400'), class: "book-img" %>
            <%if old_book.order.present?%>
            <div class='sold-out'>
              <span>SOLD OUT</span>
            </div>
            <%end%>
          </div>
          <div class='book-info'>
            <h3 class='book-name'>
              <%= old_book.old_title %>
            </h3>
            <h3 class='book-price'>
              <%= old_book.price %>円<br>
            </h3>
          </div>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>  
</div>

</div>
<%= render "shared/footer" %>