config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  devise_for :users
  root to: 'books#index'
  resources :books do
    collection do
      get 'search'
    end
    resource :favorites, only: [:create, :destroy]
  end  
  resources :old_books do
    resources :orders, only: [:index, :create]
  end
  resources :users, only: :show
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :order
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :old_books
end

app/models/book.rb
class Book < ApplicationRecord

  with_options presence: true do
    validates :isbn
    validates :read_status_id
    validates :book_review
  end  

  validates :read_status_id, numericality: { other_than: 1 , message: "can't be blank"} 

  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :read_status

  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  def favorited?(user)
    favorites.where(user_id: user.id).exists?
 end
end

app/models/book_condition.rb
class BookCondition < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '新品・未使用' },
    { id: 3, name: '未使用に近い' },
    { id: 4, name: '目立った傷や汚れなし' },
    { id: 5, name: 'やや傷や汚れあり' },
    { id: 6, name: '傷や汚れあり' },
    { id: 7, name: '全体的に状態が悪い' }
  ]

  include ActiveHash::Associations
  has_many :old_books
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '小説' },
    { id: 3, name: 'コミック' },
    { id: 4, name: '雑誌' },
    { id: 5, name: '趣味' },
    { id: 6, name: 'ビジネス' },
    { id: 7, name: 'コンピュータ・IT' },
    { id: 8, name: '人文' },
    { id: 9, name: 'アート' },
    { id: 10, name: '絵本・児童書' },
    { id: 11, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :old_books
end

app/models/delivery_charge.rb
class DeliveryCharge < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '着払い(購入者負担)' },
    { id: 3, name: '送料込み(出品者負担)' }
  ]

  include ActiveHash::Associations
  has_many :old_books
end

app/models/delivery_time.rb
class DeliveryTime < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '1~2日で発送' },
    { id: 3, name: '2~3日で発送' },
    { id: 4, name: '4~7日で発送' }
  ]

  include ActiveHash::Associations
  has_many :old_books
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/old_book.rb
class OldBook < ApplicationRecord
  has_one_attached :image
  has_one :order, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :book_condition
  belongs_to :delivery_charge
  belongs_to :area
  belongs_to :delivery_time
  belongs_to :user

  with_options presence: true do
    validates :image, :old_title, :old_book_description, :price
  end  

  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999 }

  validates :category_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :book_condition_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :delivery_charge_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :area_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :delivery_time_id, numericality: { other_than: 1, message: "can't be blank" }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :old_book
  has_one :address, dependent: :destroy
end

app/models/order_address.rb
class OrderAddress
  include ActiveModel::Model
  attr_accessor :token, :postal_code, :area_id, :city, :house_number, :building_name, :phone_number, :user_id, :old_book_id

  with_options presence: true do
    validates :postal_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: 'is invalid. Include hyphen(-)' }
    validates :city, :house_number
    validates :phone_number, format: { with: /\A\d{10,11}\z/ }
    validates :user_id, :old_book_id, :token
  end
  validates :area_id, numericality: { other_than: 1, message: "can't be blank" }

  def save
    order = Order.create(user_id: user_id, old_book_id: old_book_id)
    Address.create(postal_code: postal_code, area_id: area_id, city: city, house_number: house_number,
                           building_name: building_name, phone_number: phone_number, order_id: order.id)
  end
end

app/models/read_status.rb
class ReadStatus < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '既読' },
    { id: 3, name: '未読' }
  ]

  include ActiveHash::Associations
  has_many :books
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :last_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
    validates :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :birth_date
  end  

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX }
  
  has_many :books
  has_many :old_books
  has_many :orders

  has_many :favorites, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/old_books_helper.rb
module OldBooksHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookdock</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="https://js.pay.jp/v2/pay.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all'  %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_favorite.html.erb
<%# <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
<% if user_signed_in? %>
  <% if book.favorited?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    ♥<%= book.favorites.count %>いいね
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    ♡<%= book.favorites.count %>いいね
    <% end %>
  <% end %>
<% else %>
  <%= link_to new_user_session_path do %>
    ♡<%= book.favorites.count %>いいね
  <% end %>
<% end %>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
    </form>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='footer-contents'>
    <div class='bookdock-details'>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to '利用規約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='bookdock-details'>
      <ul>
        <li><%= link_to '読書記録', "#", class: "footer-link" %></li>
        <li><%= link_to '古本一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("logo.png", class:"bookdock-icon"), "/" %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to '読書投稿', search_books_path, class: "bookrog-list" %></li>
      <li><%= link_to '古本出品', new_old_book_path, class: "old_books-list" %></li>
    </ul>
    <ul class='lists-right'>
    <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %> </li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %> </li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    <% end %>
    </ul>
  </div>
</header>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo.png", class:"bookdock-icon"), "/" %>
</header>