config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  devise_for :users
  root to: 'books#index'
  resources :books do
    collection do
      get 'search'
    end
    resource :favorites, only: [:create, :destroy]
  end  
  resources :old_books do
    resources :orders, only: [:index, :create]
  end
  resources :users, only: :show
end

app/models/book.rb
class Book < ApplicationRecord

  with_options presence: true do
    validates :isbn
    validates :read_status_id
    validates :book_review
  end  

  validates :read_status_id, numericality: { other_than: 1 , message: "can't be blank"} 

  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :read_status

  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  def favorited?(user)
    favorites.where(user_id: user.id).exists?
 end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :contributor_confirmation, only: [:edit, :destroy]

  def index
    @books = Book.includes(:user).order('created_at DESC')
    @old_books = OldBook.includes(:user).order('created_at DESC')
  end

  def search
    @book = Book.new
    @books = RakutenWebService::Books::Book.search(title: params[:keyword]) if params[:keyword].present?
  rescue StandardError => e
    redirect_to books_url, alert: e.message
  end

  def new
      @book = Book.new(isbn: params[:isbn], title: params[:title], author: params[:author], publisher: params[:publisher], image_url: params[:image_url], item_url: params[:item_url])
      @books = RakutenWebService::Books::Book.search(title: params[:keyword]) if params[:keyword].present?
    rescue StandardError => e
      redirect_to books_url, alert: e.message
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end  

  def edit
  end  

  def update
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render :edit
    end
  end    

  def destroy
    @book.destroy
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(
      :title, :author, :image_url, :publishd_date, :publisher, :read_status_id, :book_review
  ).merge(user_id: current_user.id, isbn: params[:isbn], title: params[:title],  author: params[:author], publisher: params[:publisher], image_url: params[:image_url], item_url: params[:item_url])
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @book.user
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<%= render "shared/header" %>

  <%= form_with model: @book, url:  book_path, local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>


  <%# 本のレビュー %>
  <div class="books-contents">
    <div class="books-detail">
      <div class="form">
        <%= image_tag @book.image_url %>
        <div class="weight-bold-text">
        <h2>タイトル</h2>
          <span class="indispensable"></span>
        </div>
        <%= @book.title %>
        <div class="weight-bold-text">
        <h2>著者</h2>
          <span class="indispensable"></span>
        </div>
        <%= @book.author %>
        <div class="weight-bold-text">
        <h2>出版社</h2>
          <span class="indispensable"></span>
        </div>
        <%= @book.publisher %>
        <div class="weight-bold-text">
        <h2>読書状況</h2>
          <span class="indispensable"></span>
        </div>
        <%= f.collection_select(:read_status_id, ReadStatus.all, :id, :name, {}, {class:"genre-select"}) %>
        <div class="weight-bold-text">
        <h2>読書レビュー</h2>
          <span class="indispensable"></span>
        </div>
        <%= f.text_area :book_review, class:"items-text", id:"book-info", placeholder:"読書レビュー" ,rows:"7" ,maxlength:"1000" %>
        <%= hidden_field_tag :isbn, @book.isbn %>
        <%= hidden_field_tag :title, @book.title %>
        <%= hidden_field_tag :author, @book.author %>
        <%= hidden_field_tag :publisher, @book.publisher %>
        <%= hidden_field_tag :image_url, @book.image_url %>
        <%= hidden_field_tag :item_url, @book.item_url %>
      </div>
    </div>
  <%# /本のレビュー %>
    <%= f.submit "投稿する" ,class:"sell-btn" %> 

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%=link_to 'もどる', book_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/books/index.html.erb
<%= render "shared/header" %>

<div class='main'>

  <div class='title-contents'>
    <h2 class='service-title'>
      bookdockが読書を変える
    </h2>
    <p class='service-explain'>
      読書記録はもちろん、積読本をかんたんに出品・購入できる
    </p>
  </div>

  <%# 読書一覧 %>
  <div class='book-contents'>
    <h2 class='title'>本日のおすすめ</h2>
    <div class="subtitle" >
      読書投稿一覧
    </div>
    <ul class='book-lists'>
      <% @books.each do |book| %>
      <li class='list'>
        <%= link_to book_path(book.id) do %>
        <div class='book-img-content'>
          <%= image_tag book.image_url,  class: "book-img" %>
        </div>
        <div class='book-info'>
          <h3 class='book-name'>
            <%= book.title %>
          </h3>
          <a href="/users/<%= book.user.id %>">
            <span>投稿者</span><%= book.user.nickname %>
          </a>
          <div class='star-btn'>
            <%= image_tag "star.png", class:"star-icon" %>
            <span class='star-count'>
              <%= book.favorites.count %>いいね
            </span>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
  <%# /読書一覧 %>

  <%# /古本一覧 %>
  <div class='book-contents'>
    <h2 class='title'>本日のおすすめ</h2>
    <div class="subtitle" >
      古本出品一覧
    </div>
    <ul class='book-lists'>
          <% @old_books.each do |old_book| %>
      <li class='list'>
        <%= link_to old_book_path(old_book.id) do %>
        <div class='book-img-content'>
          <%= image_tag old_book.image.variant(resize: '400x400'), class: "book-img" %>
          <%if old_book.order.present?%>
          <div class='sold-out'>
            <span>SOLD OUT</span>
          </div>
          <%end%>
        </div>
        <div class='book-info'>
          <h3 class='book-name'>
            <%= old_book.old_title %>
          </h3>
          <h3 class='book-price'>
            <%= old_book.price %>円<br>
          </h3>
          <a href="/users/<%= old_book.user.id %>">
            <span>出品者</span><%= old_book.user.nickname %>
          </a>
        </div>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
  <%# /古本一覧 %>

  <div class='ad-contents'>
    <h2 class='service-title'>
      読書か、出品か
    </h2>
    <p class='service-explain'>
      いつかのあの本に出会えるかもしれません
    </p>
  </div>

</div>
<%= render "shared/footer" %>

app/views/books/new.html.erb
<%= render "shared/header" %>

  <%= form_with model: @book, url:  books_path, method: :post, local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>


  <%# 本のレビュー %>
  <div class="books-contents">
    <div class="books-detail">
      <div class="form">
        <%= image_tag @book.image_url %>
        <div class="weight-bold-text">
        <h2>タイトル</h2>
          <span class="indispensable"></span>
        </div>
        <%= @book.title %>
        <div class="weight-bold-text">
        <h2>ISBN</h2>
          <span class="indispensable"></span>
        </div>
        <%= @book.isbn %>
        <div class="weight-bold-text">
        <h2>著者</h2>
          <span class="indispensable"></span>
        </div>
        <%= @book.author %>
        <div class="weight-bold-text">
        <h2>出版社</h2>
          <span class="indispensable"></span>
        </div>
        <%= @book.publisher %>
        <div class="weight-bold-text">
          <h2>読書状況</h2>
          <span class="indispensable"></span>
        </div>
        <%= f.collection_select(:read_status_id, ReadStatus.all, :id, :name, {}, {class:"genre-select"}) %>
        <div class="weight-bold-text">
          <h2>読書レビュー</h2>
          <span class="indispensable"></span>
        </div>
        <%= f.text_area :book_review, class:"items-text", id:"book-info", placeholder:"読書レビュー" ,rows:"7" ,maxlength:"1000" %>
        <%= hidden_field_tag :isbn, @book.isbn %>
        <%= hidden_field_tag :title, @book.title %>
        <%= hidden_field_tag :author, @book.author %>
        <%= hidden_field_tag :publisher, @book.publisher %>
        <%= hidden_field_tag :image_url, @book.image_url %>
        <%= hidden_field_tag :item_url, @book.item_url %>
      </div>
    </div>
  <%# /本のレビュー %>
    <%= f.submit "投稿する" ,class:"sell-btn" %> 

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/books/search.html.erb
<%= render "shared/header" %>

<div class="books-contents">
<%= form_with model: @book, url: search_books_path, method: :get, local: true do |f| %>

  <%# 商品名と商品説明 %>
  <div class="books-main">
    <h2 class="books-title">
      タイトルを検索
    </h2>
  <div class="search-box">
      <%= text_field_tag :keyword, "",  id: "book_search", name: "keyword", placeholder: "タイトルを入力してください", style: "width: 220px;"%><button title="検索" type="submit">検索</button>
      <% end %>
    
    <%= form_with model: @book, url: new_book_path, method: :get, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="books-sub">
    <h2 class="books-title">検索結果</h2>
      <div class='book-lists'>
        <% if @books.present? %>
        <% @books.each do |book| %>
          <div class="item-list-area">
            <%= link_to (image_tag(book.medium_image_url)), book.item_url %>
            <h2 class='book-search'>
              <%= book.title %>
            </h2>
            <h2 class='book-search'>
              <%= book.author %>
            </h2>  
            <h2 class='book-search'> 
              <%= book.publisher_name %>
            </h2>
            <h2 class='book-search'>  
              <%= book.sales_date %>
            </h2>  
              <%= form_tag(new_book_path, method: :get) do %>
              <%= hidden_field_tag :isbn, book.isbn %>
              <%= hidden_field_tag :title, book.title %>
              <%= hidden_field_tag :author, book.author %>
              <%= hidden_field_tag :publisher, book.publisher_name %>
              <%= hidden_field_tag :image_url, book.medium_image_url %>
              <%= hidden_field_tag :item_url, book.item_url %>
              <%= f.submit "選択する" ,class:"sell-btn" %>
            <% end %>
          </div> 
          <% end %>     
        <% end %>
      </div>
    </div>
  </div>
  <%# /商品名と商品説明 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/books/show.html.erb
<%= render "shared/header" %>

<%# 読書の概要 %>
<div class="item-show">
  <div class="item-box">    
    <div class="item-img-content">
      <%= link_to (image_tag(@book.image_url)), @book.item_url %>
    </div>
    <div class="item-price-box">
      <span class="item-postage">
        <h2>タイトル</h2>
      </span>
      <%= @book.title %>
      <span class="item-postage">
        <h2>ISBN</h2>
      </span>
      <%= @book.isbn %>
      <span class="item-postage">
        <h2>著者</h2>
      </span>
      <%= @book.author %>
      <span class="item-postage">
        <h2>出版社</h2>
      </span>
      <%= @book.publisher %>
    </div>

    <% if user_signed_in? %>
      <% if current_user.id == @book.user_id %>
        <%= link_to "レビューの編集", edit_book_path(@book), method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", book_path(@book), method: :delete, class:"item-destroy" %>
      <% end %>
    <% end %>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">ユーザー</th>
          <td class="detail-value"><%= @book.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">読書状況</th>
          <td class="detail-value"><%= @book.read_status.name %></td>
        </tr>
        <tr>
          <th class="detail-item">レビュー</th>
          <td class="detail-value"><%= @book.book_review %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div id = "favorite_btn_<%= @book.id %>">
  <%= render "shared/favorite" , book: @book%>
  <%# /読書の概要 %>

<%= render "shared/footer" %>